# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
targets:

  $default:
    sources:
      {"exclude" : ["bin/**"]}
    builders:
      build_web_compilers|dart2js_archive_extractor:
        options:
          filter_outputs: true
      build_web_compilers|entrypoint:
        generate_for:
          - example/coin/example.dart
          - example/goblins/example.dart
          - example/hero/example.dart
          - example/powerup/example.dart
          - example/raptor/example.dart
          - example/spineboy/example.dart
          - example/stretchyman/example.dart
          - example/tank/example.dart
          - example/texture_atlas/example.dart
          - example/vine/example.dart
        dev_options:
          compiler: dartdevc
        release_options:
          compiler: dart2js
          dart2js_args:
           # See https://webdev.dartlang.org/tools/dart2js#size-and-speed-options
           # - --dump-info
            - --fast-startup
            - --minify
            - --no-frequency-based-minification
            - --no-source-maps
            - --show-package-warnings
            - --trust-primitives
            - --trust-type-annotations